// packages/solid-js/src/Translate.tsx
import type { TinyIntlTranslateTemplate } from '@tiny-intl/core';
import type { JSX } from 'solid-js';

import { Show, createMemo, createSignal, onCleanup, onMount, useContext } from 'solid-js';

import { TinyIntlContext } from './useIntl';

export type TranslateProps = {
  children?: (value: string | null) => JSX.Element;
} & (
  | {
      // Case: string translation
      name: string;
      count?: number;
      date?: undefined;
      number?: undefined;
      options?: TinyIntlTranslateTemplate;
      relative?: undefined;
      unit?: undefined;
    }
  | {
      // Case: dateFormat
      name?: undefined;
      count?: undefined;
      data?: undefined;
      date?: Date | string | number;
      number?: undefined;
      options?: Intl.DateTimeFormatOptions;
      relative?: undefined;
    }
  | {
      // Case: relativeTimeFormat
      name?: undefined;
      count?: undefined;
      data?: undefined;
      date?: Date | string | number;
      number?: undefined;
      options?: Intl.RelativeTimeFormatOptions;
      relative?: true;
    }
  | {
      // Case: numberFormat
      name?: undefined;
      count?: undefined;
      data?: undefined;
      date?: undefined;
      number?: number;
      options?: Intl.NumberFormatOptions;
      relative?: undefined;
    }
);

export function Translate(props: TranslateProps) {
  const intl = useContext(TinyIntlContext);

  if (!intl) {
    throw new Error('useIntl must be used within a TinyIntlContext.Provider');
  }

  const [changed, setChanged] = createSignal(0);

  const translateFn = createMemo(
    () => {
      changed();

      if (props.count) {
        return intl.tc(props.name, props.count, props.options);
      }

      if (props.date && !props.relative) {
        return intl.dt(props.date, props.options);
      }

      if (props.date && props.relative) {
        return intl.rt(props.date, props.options);
      }

      if (props.number) {
        return intl.n(props.number, props.options);
      }

      if (props.name) {
        return intl.t(props.name, props.options);
      }

      return null;
    },
    null,
    {
      equals: (a, b) => a === b,
    },
  );

  onMount(() => {
    const dispose = intl.subscribe(() => {
      setChanged((prev) => prev + 1);
    });
    onCleanup(() => {
      dispose();
    });
  });

  return (
    <Show
      when={typeof props.children === 'function' && props.children}
      keyed
      fallback={translateFn()}
    >
      {(childFn) => childFn(translateFn())}
    </Show>
  );
}

export const Trans = Translate;

// packages/react/src/Translate.tsx
/* eslint-disable react-hooks/exhaustive-deps */
import type { TinyIntlTranslateTemplate } from '@tiny-intl/core';

import { useCallback, useContext, useEffect, useState } from 'react';

import { TinyIntlContext } from './useIntl';

export type TranslateProps = {
  children?: (value: string | null) => React.ReactNode;
} & (
  | {
      // Case: string translation
      name: string;
      count?: number;
      date?: undefined;
      number?: undefined;
      options?: TinyIntlTranslateTemplate;
      relative?: undefined;
      unit?: undefined;
    }
  | {
      // Case: dateFormat
      name?: undefined;
      count?: undefined;
      data?: undefined;
      date?: Date | string | number;
      number?: undefined;
      options?: Intl.DateTimeFormatOptions;
      relative?: undefined;
    }
  | {
      // Case: relativeTimeFormat
      name?: undefined;
      count?: undefined;
      data?: undefined;
      date?: Date | string | number;
      number?: undefined;
      options?: Intl.RelativeTimeFormatOptions;
      relative?: true;
    }
  | {
      // Case: numberFormat
      name?: undefined;
      count?: undefined;
      data?: undefined;
      date?: undefined;
      number?: number;
      options?: Intl.NumberFormatOptions;
      relative?: undefined;
    }
);

export function Translate(props: TranslateProps) {
  const intl = useContext(TinyIntlContext);

  if (!intl) {
    throw new Error('useIntl must be used within a TinyIntlContext.Provider');
  }

  const { subscribe, t, tc, dt, n, rt } = intl;
  const { name, count, date, number, options, children, relative } = props; // eslint-disable-line no-shadow

  const [changed, setChanged] = useState(0);

  const translateFn = useCallback(() => {
    if (count != null) {
      return tc(name, count, options);
    }

    if (date != null && !relative) {
      return dt(date, options);
    }

    if (date != null && relative) {
      return rt(date, options);
    }

    if (number != null) {
      return n(number, options);
    }

    if (name) {
      return t(name, options);
    }

    return null;
  }, [changed, count, date, name, number, options, relative]);

  useEffect(() => {
    const dispose = subscribe(() => {
      setChanged((prev) => prev + 1);
    });
    return dispose;
  }, [intl]);

  if (children && typeof children === 'function') {
    return <>{children(translateFn())}</>;
  }

  return <>{translateFn()}</>;
}

export const Trans = Translate;
